version: '3.8'
services:
  eigenda-proxy:
    image: ghcr.io/layr-labs/eigenda-proxy:2.2.1
    ports:
      - "3100:3100"
    env_file:
      - .env.eigenda.sepolia
    command: [
      "--addr", "0.0.0.0",
      "--port", "3100",
      "--api-enabled", "admin"
    ]

  nitro-node:
    image: ghcr.io/layr-labs/nitro/nitro-node:v3.8.0
    container_name: hpp-node-sepolia
    volumes:
      - ./hpp-sepolia-node-config.json:/config/nodeConfig.json
      - ./hpp-sepolia/data:/home/user/.arbitrum
      - ./hpp-sepolia/latest-sepolia.tar:/home/user/snapshots.tar
    ports:
      - "8547:8547"
      - "8548:8548"
    command:
      [
        "--init.url", "file:///home/user/snapshots.tar",
        "--conf.file", "/config/nodeConfig.json",
        # Passing the configurations of http because they are not working by config file, but I don't know why.
        "--http.api", "web3,net,eth",
        "--http.addr", "0.0.0.0",
        "--http.corsdomain", "*"
      ]
    restart: unless-stopped
    depends_on:
      - eigenda-proxy
